import './globals.css'
import './bootstrap.min.css'
import { Inter } from 'next/font/google'
import NavBarPage from '@/components/NavbarPage'
import FooterPage from '@/components/FooterPage'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarPage />
        <div className='container-fluid'>
          {children}
        </div>
        <FooterPage />
        </body>
    </html>
  )
}
